[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$EngineBin,[Parameter(Mandatory=$true)][string]$CasePath,[Parameter(Mandatory=$true)][string]$SourceRoot,[Parameter(Mandatory=$true)][string]$OutputPath,[string]$DwsimRevision="9.0.5.0")
$ErrorActionPreference="Stop";Set-StrictMode -Version Latest
function Number([string]$value){if([string]::IsNullOrWhiteSpace($value)){return 0.0};return [double]::Parse($value,[Globalization.CultureInfo]::InvariantCulture)}
$engine=(Resolve-Path -LiteralPath $EngineBin).Path;$case=(Resolve-Path -LiteralPath $CasePath).Path;$source=(Resolve-Path -LiteralPath $SourceRoot).Path;$assembly=Join-Path $engine "DWSIM.Thermodynamics.AdvancedEOS.PCSAFT2.dll";$packageSource=Join-Path $source "DWSIM.Thermodynamics.AdvancedEOS.PCSAFT\PCSAFT2PropertyPackage.vb";$eosSource=Join-Path $source "DWSIM.Thermodynamics.AdvancedEOS.PCSAFT\PCSAFT2.vb";$pureSource=Join-Path $source "DWSIM.Thermodynamics.AdvancedEOS.PCSAFT\Data\pcsaft.dat";$interactionSource=Join-Path $source "DWSIM.Thermodynamics.AdvancedEOS.PCSAFT\Data\pcsaft_ip.dat"
foreach($f in @($assembly,$case,$packageSource,$eosSource,$pureSource,$interactionSource)){if(-not(Test-Path -LiteralPath $f)){throw "Missing required file: $f"}}
$pure=@();foreach($row in (Import-Csv -LiteralPath $pureSource -Delimiter "`t")){$pure+=,[ordered]@{source_name=$row.compound;cas_number=$row.cas_no;molecular_weight=(Number $row.mw);segment_count=(Number $row.m);segment_diameter_angstrom=(Number $row.sigma_A);dispersion_energy_k=(Number $row.epsilon_k_K);association_volume=(Number $row.kAiBi);association_energy_k=(Number $row.epsilon_AiBi_k_K)}}
$interactions=@();foreach($row in (Import-Csv -LiteralPath $interactionSource -Delimiter "`t")){$interactions+=,[ordered]@{source_name_1=$row.comp1;cas_number_1=$row.cas1;source_name_2=$row.comp2;cas_number_2=$row.cas2;kij=(Number $row.kij)}}
$doc=[ordered]@{schema_version="dwsim-pcsaft-data-1";model="PC-SAFT (with Association Support) (.NET Code)";source=[ordered]@{product="DWSIM";revision=$DwsimRevision;case_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $case).Hash.ToLowerInvariant();runtime_assembly_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $assembly).Hash.ToLowerInvariant();property_package_source_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $packageSource).Hash.ToLowerInvariant();eos_source_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $eosSource).Hash.ToLowerInvariant();pure_data_source_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $pureSource).Hash.ToLowerInvariant();interaction_data_source_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $interactionSource).Hash.ToLowerInvariant()};scoped_compounds=@([ordered]@{compound_id="Methane";cas_number="74-82-8"},[ordered]@{compound_id="Ethane";cas_number="74-84-0"});pure_parameters=$pure;interaction_parameters=$interactions}
$out=[IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputPath));$dir=Split-Path -Parent $out;if($dir){New-Item -ItemType Directory -Force -Path $dir|Out-Null};$doc|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $out -Encoding utf8
[ordered]@{output=$out;pure_parameter_count=$pure.Count;interaction_count=$interactions.Count;sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $out).Hash.ToLowerInvariant()}|ConvertTo-Json
