[CmdletBinding()]
param([Parameter(Mandatory=$true)][string]$EngineBin,[Parameter(Mandatory=$true)][string]$CasePath,[Parameter(Mandatory=$true)][string]$SourceRoot,[Parameter(Mandatory=$true)][string]$OutputPath,[string]$DwsimRevision="9.0.5.0",[double]$TemperatureK=350,[string]$CompositionCsv="0.98,0.02")
$ErrorActionPreference="Stop";Set-StrictMode -Version Latest
$composition=@($CompositionCsv.Split(",")|ForEach-Object{[double]::Parse($_,[Globalization.CultureInfo]::InvariantCulture)})
Add-Type -TypeDefinition @"
using System;using System.Collections;using System.Globalization;using System.Linq;using System.Reflection;
public static class DwsimSeawaterExtractor{
 static BindingFlags F=BindingFlags.Public|BindingFlags.Instance;
 static object I(object o,string n,object[] a,int c){return o.GetType().GetMethods(F).First(x=>x.Name==n&&x.GetParameters().Length==c).Invoke(o,a);}
 static void S(object o,string n,object v){o.GetType().GetProperties(F).First(x=>x.Name==n&&x.CanWrite&&x.GetIndexParameters().Length==0).SetValue(o,v,null);}
 public static object[] Create(object automation){object fs=I(automation,"CreateFlowsheet",new object[0],0);I(fs,"AddCompound",new object[]{"Water"},1);I(fs,"AddCompound",new object[]{"Salt"},1);var add=fs.GetType().GetMethods(F).First(x=>x.Name=="AddObject"&&x.GetParameters().Length==4);object mt=Enum.Parse(add.GetParameters()[0].ParameterType,"MaterialStream",true);object ms=add.Invoke(fs,new object[]{mt,50,50,"thermo probe"});Type t=AppDomain.CurrentDomain.GetAssemblies().Select(a=>a.GetType("DWSIM.Thermodynamics.PropertyPackages.SeawaterPropertyPackage",false,false)).First(x=>x!=null);object pp=Activator.CreateInstance(t);S(pp,"ComponentName","Seawater");S(pp,"Flowsheet",fs);S(pp,"CurrentMaterialStream",ms);return new object[]{fs,pp};}
 public static string[] Names(object pp){return((IEnumerable)I(pp,"RET_VNAMES",new object[0],0)).Cast<object>().Select(Convert.ToString).ToArray();}
 public static double[] MW(object pp){return((IEnumerable)I(pp,"RET_VMM",new object[0],0)).Cast<object>().Select(x=>Convert.ToDouble(x,CultureInfo.InvariantCulture)).ToArray();}
 public static double[] Mass(object pp,double[] z){return((IEnumerable)I(pp,"AUX_CONVERT_MOL_TO_MASS",new object[]{z},1)).Cast<object>().Select(x=>Convert.ToDouble(x,CultureInfo.InvariantCulture)).ToArray();}
 public static double Salinity(object pp,double[] z){return Convert.ToDouble(I(pp,"CalcSalinity",new object[]{z},1),CultureInfo.InvariantCulture);}
 public static double CurrentSalinity(object pp){return Convert.ToDouble(I(pp,"CalcSalinity",new object[0],0),CultureInfo.InvariantCulture);}
 public static double VaporPressure(object pp,double[] z,double t){return Convert.ToDouble(I(pp,"VaporPressure",new object[]{z,t},2),CultureInfo.InvariantCulture);}
}
"@
$engine=(Resolve-Path -LiteralPath $EngineBin).Path;$case=(Resolve-Path -LiteralPath $CasePath).Path;$source=(Resolve-Path -LiteralPath $SourceRoot).Path;$assembly=Join-Path $engine "DWSIM.Thermodynamics.dll";$packageSource=Join-Path $source "DWSIM.Thermodynamics\PropertyPackages\SeaWater.vb";$modelSource=Join-Path $source "DWSIM.Thermodynamics\PropertyPackages\Models\Seawater.vb"
foreach($f in @((Join-Path $engine "DWSIM.Interfaces.dll"),(Join-Path $engine "DWSIM.Automation.dll"),$assembly,$case,$packageSource,$modelSource)){if(-not(Test-Path -LiteralPath $f)){throw "Missing required file: $f"}}
[Reflection.Assembly]::LoadFrom((Join-Path $engine "DWSIM.Interfaces.dll"))|Out-Null;$tc=Get-ChildItem $engine -Filter ThermoCS.dll -File -Recurse -ErrorAction SilentlyContinue|Select-Object -First 1;if($null-ne$tc){[Reflection.Assembly]::LoadFrom($tc.FullName)|Out-Null};[Reflection.Assembly]::LoadFrom($assembly)|Out-Null;[Reflection.Assembly]::LoadFrom((Join-Path $engine "DWSIM.Automation.dll"))|Out-Null
$auto=New-Object DWSIM.Automation.Automation3;$objects=[DwsimSeawaterExtractor]::Create($auto);$pp=$objects[1];$names=[DwsimSeawaterExtractor]::Names($pp);$mw=[DwsimSeawaterExtractor]::MW($pp);$mass=[DwsimSeawaterExtractor]::Mass($pp,$composition);$salinity=[DwsimSeawaterExtractor]::Salinity($pp,$composition);$currentSalinity=[DwsimSeawaterExtractor]::CurrentSalinity($pp);$vaporPressure=[DwsimSeawaterExtractor]::VaporPressure($pp,$composition,$TemperatureK)
$text=Get-Content -LiteralPath $modelSource -Raw;$matches=[regex]::Matches($text,"(?m)^\s*Dim a As Double\(\) = New Double\(\) \{0,\s*\r?\n\s*(-5800\.2206[\s\S]*?)\}");if($matches.Count-ne1){throw "Could not uniquely locate seawater vapor-pressure coefficients"};$numbers=[regex]::Matches($matches[0].Groups[1].Value,"[-+]?[0-9]+(?:\.[0-9]+)?(?:[Ee][-+]?[0-9]+)?")|ForEach-Object{[double]::Parse($_.Value,[Globalization.CultureInfo]::InvariantCulture)}
$doc=[ordered]@{schema_version="dwsim-seawater-data-1";model="Seawater";source=[ordered]@{product="DWSIM";revision=$DwsimRevision;case_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $case).Hash.ToLowerInvariant();runtime_assembly_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $assembly).Hash.ToLowerInvariant();property_package_source_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $packageSource).Hash.ToLowerInvariant();model_source_sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $modelSource).Hash.ToLowerInvariant()};compound_ids=$names;molecular_weights=$mw;salinity_limit=0.12;vapor_pressure_coefficients=@($numbers);scoped_probe=[ordered]@{temperature_k=$TemperatureK;composition=$composition;converted_mass_fractions=$mass;calculated_salinity=$salinity;current_stream_salinity=$currentSalinity;vapor_pressure_pa=$vaporPressure}}
$out=[IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputPath));$dir=Split-Path -Parent $out;if($dir){New-Item -ItemType Directory -Force -Path $dir|Out-Null};$doc|ConvertTo-Json -Depth 8|Set-Content -LiteralPath $out -Encoding utf8
[ordered]@{output=$out;salinity=$salinity;vapor_pressure_pa=$vaporPressure;sha256=(Get-FileHash -Algorithm SHA256 -LiteralPath $out).Hash.ToLowerInvariant()}|ConvertTo-Json
